spring:
    config:
        import: env.yml
    datasource:
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/${DB_DATABASE_NAME}
        username: ${DB_USER}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update